name: befab
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.0
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  fl_chart: ^1.0.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0
  socket_io_client: ^2.0.3+1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  path_provider: ^2.1.3
  health: ^13.1.2
  permission_handler: ^11.3.0
  mobile_scanner: ^3.1.0
  shared_preferences: ^2.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
